### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by Stebalien**
* Update golang to 1.12.9
* Update debian to buster
* Update go-ipfs to 0.4.22
* Update node to 12

### CODE REVIEW

**Comment by olizilla** [comment]
You'll be delighted to hear this causes all sorts of issues... I can't get this docker image to build at all. `ageir` install fails due to permissions issues, and the `dnslink-dnsimple` due to:

```
+ go get -v github.com/lgierth/dnslink-dnsimple
github.com/lgierth/dnslink-dnsimple (download)
github.com/dnsimple/dnsimple-go (download)
github.com/google/go-querystring (download)
github.com/google/go-querystring/query
github.com/dnsimple/dnsimple-go/dnsimple
github.com/lgierth/dnslink-dnsimple
# github.com/lgierth/dnslink-dnsimple
src/github.com/lgierth/dnslink-dnsimple/main.go:33:31: undefined: dnsimple.NewOauthTokenCredentials
```

while the  godoc2md fails with

```
golang.org/x/tools/godoc
github.com/davecheney/godoc2md
# github.com/davecheney/godoc2md
src/github.com/davecheney/godoc2md/main.go:173:6: pres.ShowExamples undefined (type *godoc.Presentation has no field or method ShowExamples)
src/github.com/davecheney/godoc2md/main.go:175:6: pres.SrcMode undefined (type *godoc.Presentation has no field or method SrcMode)
src/github.com/davecheney/godoc2md/main.go:176:6: pres.HTMLMode undefined (type *godoc.Presentation has no field or method HTMLMode)
src/github.com/davecheney/godoc2md/main.go:184:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
src/github.com/davecheney/godoc2md/main.go:186:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
src/github.com/davecheney/godoc2md/main.go:189:12: undefined: godoc.CommandLine
```

**Comment by olizilla** [comment]
I have a fix for the aegir issue. Will push that to this branch

**Comment by olizilla** [comment]
I don't think we need dnslink-dnsimple for this image, I dont think anyone is using it apart from the docs site. If we do need it, I published the js port of that module to npm last week, so we can get it from there.

**Comment by Stebalien** [comment]
@olizilla it _should_ now build. However, the API for dnslink-dnsimple has changed slightly.

I'd also be happy to switch to the js port.

**Review by olizilla — APPROVED** [review]
👍  it work!

**Pull request merged**
